environment:
  matrix:
    - nodejs_version: "10.0.0"
    - nodejs_version: "12.0.0"

platform:
  - x64

matrix:
  fast_finish: true

clone_depth: 50

configuration:
  - Release

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - appveyor-retry npm install

test_script:
  - npm run lint
  - appveyor-retry npm test

build: false
